# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Deploy to EC2

# Gatilho: o workflow roda quando houver um merge na branch 'master'
on:
  pull_request:
    branches: [ "master" ]
    types: [ closed ]
  # Permite também rodar este workflow manualmente pela interface do GitHub
  workflow_dispatch:

jobs:
  # Nome do nosso job
  build-and-deploy:
    
    runs-on: self-hosted
    
    # Variáveis de ambiente disponíveis em todo o job
    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      # Verifica se o PR foi mergeado (não apenas fechado)
      - name: Verificar se foi merge
        if: github.event.pull_request.merged == true
        run: echo "PR foi mergeado, continuando com o deploy..."

      # 1. Pega o código do seu repositório para dentro do runner
      - name: Checkout do código
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v4

      # 2. Faz login no Docker Hub usando os secrets que configuramos
      - name: Login no Docker Hub
        if: github.event.pull_request.merged == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Builda a imagem Docker e envia (push) para o Docker Hub
      - name: Build e Push da Imagem Docker
        if: github.event.pull_request.merged == true
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # IMPORTANTE: Substitua com seu usuário e nome do repositório no Docker Hub
          tags: lcsszltda/app:latest

      # 4. Faz o deploy no servidor usando o Docker Compose
      - name: Deploy com Docker Compose
        if: github.event.pull_request.merged == true
        run: |
          # Cria o arquivo .env no servidor antes do deploy
          echo "API_KEY=${{ secrets.API_KEY }}" > .env
          echo "Arquivo .env criado no servidor com sucesso!"
          
          # Faz o deploy
          docker compose pull
          docker compose up -d



